from .s3_compat import S3CompatProvider
from .aliyun_oss import AliyunOSSProvider
from .tencent_cos import TencentCOSProvider
from .qiniu_kodo import QiniuKodoProvider
from .webdav import WebDAVProvider
from .onedrive import OneDriveProvider

PROVIDER_REGISTRY = {
    'aliyun_oss': {
        'name': '阿里云 OSS',
        'protocol': 'native',
        'sdk': 'oss2',
        'provider_class': AliyunOSSProvider,
        'params': ['access_key', 'secret_key', 'endpoint', 'bucket'],
        'endpoint_template': 'https://oss-cn-<region>.aliyuncs.com',
        'region_options': [
            'cn-beijing', 'cn-shanghai', 'cn-guangzhou', 'cn-shenzhen',
            'cn-chengdu', 'cn-hangzhou', 'cn-nanjing', 'cn-qingdao',
            'cn-hongkong', 'ap-southeast-1',
        ],
        'icon': 'aliyun',
        'need_bucket': True,
        'need_region': True,
        'need_endpoint': True,
        'supports_bucket_cors': True,
        'supports_bucket_acl': True,
        'supports_multipart_management': True,
    },
    'tencent_cos': {
        'name': '腾讯云 COS',
        'protocol': 'native',
        'sdk': 'cos-python-sdk-v5',
        'provider_class': TencentCOSProvider,
        'params': ['access_key', 'secret_key', 'region', 'bucket'],
        'region_options': [
            'ap-beijing', 'ap-shanghai', 'ap-guangzhou', 'ap-chengdu',
            'ap-nanjing', 'ap-chongqing', 'ap-hongkong', 'ap-singapore',
        ],
        'icon': 'tencent',
        'need_bucket': True,
        'need_region': True,
        'need_endpoint': False,
        'supports_bucket_cors': True,
        'supports_bucket_acl': True,
        'supports_multipart_management': True,
    },
    'huawei_obs': {
        'name': '华为云 OBS',
        'protocol': 's3',
        'sdk': 'boto3',
        'provider_class': S3CompatProvider,
        'params': ['access_key', 'secret_key', 'endpoint', 'region', 'bucket'],
        'endpoint_template': 'https://obs.<region>.myhuaweicloud.com',
        'region_options': [
            'cn-north-1', 'cn-north-4', 'cn-east-2', 'cn-east-3',
            'cn-south-1', 'cn-south-2', 'cn-southwest-2', 'ap-southeast-1',
        ],
        's3_path_style': False,
        'icon': 'huawei',
        'need_bucket': True,
        'need_region': True,
        'need_endpoint': True,
        'supports_bucket_cors': True,
        'supports_bucket_acl': True,
        'supports_multipart_management': True,
    },
    'baidu_bos': {
        'name': '百度云 BOS',
        'protocol': 's3',
        'sdk': 'boto3',
        'provider_class': S3CompatProvider,
        'params': ['access_key', 'secret_key', 'endpoint', 'region', 'bucket'],
        'endpoint_template': 'https://s3.<region>.bcebos.com',
        'region_options': ['bj', 'gz', 'su', 'hkg', 'fwh'],
        's3_path_style': True,
        'icon': 'baidu',
        'need_bucket': True,
        'need_region': True,
        'need_endpoint': True,
        'supports_bucket_cors': True,
        'supports_bucket_acl': True,
        'supports_multipart_management': True,
    },
    'jd_oss': {
        'name': '京东云 OSS',
        'protocol': 's3',
        'sdk': 'boto3',
        'provider_class': S3CompatProvider,
        'params': ['access_key', 'secret_key', 'endpoint', 'region', 'bucket'],
        'endpoint_template': 'https://s3.<region>.jdcloud-oss.com',
        'region_options': ['cn-north-1', 'cn-south-1', 'cn-east-2'],
        's3_path_style': False,
        'icon': 'jd',
        'need_bucket': True,
        'need_region': True,
        'need_endpoint': True,
        'supports_bucket_cors': True,
        'supports_bucket_acl': True,
        'supports_multipart_management': True,
    },
    'ks_ks3': {
        'name': '金山云 KS3',
        'protocol': 's3',
        'sdk': 'boto3',
        'provider_class': S3CompatProvider,
        'params': ['access_key', 'secret_key', 'endpoint', 'region', 'bucket'],
        'endpoint_template': 'https://ks3.<region>.kscs.com',
        'region_options': ['cn-beijing', 'cn-shanghai', 'cn-guangzhou', 'cn-hongkong'],
        's3_path_style': False,
        'icon': 'ks',
        'need_bucket': True,
        'need_region': True,
        'need_endpoint': True,
        'supports_bucket_cors': True,
        'supports_bucket_acl': True,
        'supports_multipart_management': True,
    },
    'ctyun_zos': {
        'name': '天翼云 ZOS',
        'protocol': 's3',
        'sdk': 'boto3',
        'provider_class': S3CompatProvider,
        'params': ['access_key', 'secret_key', 'endpoint', 'region', 'bucket'],
        'endpoint_template': 'https://zos.<region>.ctyunapi.cn',
        'region_options': ['cn-ctyun1'],
        's3_path_style': False,
        'icon': 'ctyun',
        'need_bucket': True,
        'need_region': True,
        'need_endpoint': True,
        'supports_bucket_cors': True,
        'supports_bucket_acl': True,
        'supports_multipart_management': True,
    },
    'cloudflare_r2': {
        'name': 'Cloudflare R2',
        'protocol': 's3',
        'sdk': 'boto3',
        'provider_class': S3CompatProvider,
        'params': ['access_key', 'secret_key', 'endpoint', 'region', 'bucket'],
        'endpoint_template': 'https://<account_id>.r2.cloudflarestorage.com',
        's3_path_style': False,
        'icon': 'cloudflare',
        'need_bucket': True,
        'need_region': False,
        'need_endpoint': True,
        'supports_bucket_cors': True,
        'supports_bucket_acl': True,
        'supports_multipart_management': True,
    },
    'google_gcs': {
        'name': '谷歌云存储',
        'protocol': 's3',
        'sdk': 'boto3',
        'provider_class': S3CompatProvider,
        'params': ['access_key', 'secret_key', 'endpoint', 'region', 'bucket'],
        'endpoint_template': 'https://storage.googleapis.com',
        's3_path_style': True,
        'icon': 'google',
        'need_bucket': True,
        'need_region': True,
        'need_endpoint': True,
        'supports_bucket_cors': True,
        'supports_bucket_acl': True,
        'supports_multipart_management': True,
    },
    'qiniu_kodo': {
        'name': '七牛云 Kodo',
        'protocol': 'native',
        'sdk': 'qiniu',
        'provider_class': QiniuKodoProvider,
        'params': ['access_key', 'secret_key', 'bucket'],
        'icon': 'qiniu',
        'need_bucket': True,
        'need_region': False,
        'need_endpoint': False,
        'supports_bucket_cors': False,
        'supports_bucket_acl': False,
        'supports_multipart_management': False,
    },
    'minio': {
        'name': 'MinIO',
        'protocol': 's3',
        'sdk': 'boto3',
        'provider_class': S3CompatProvider,
        'params': ['access_key', 'secret_key', 'endpoint', 'bucket'],
        'endpoint_template': 'http://<host>:9000',
        's3_path_style': True,
        'icon': 'minio',
        'need_bucket': True,
        'need_region': False,
        'need_endpoint': True,
        'supports_bucket_cors': True,
        'supports_bucket_acl': True,
        'supports_multipart_management': True,
    },
    'webdav': {
        'name': 'WebDAV',
        'protocol': 'webdav',
        'sdk': 'webdavclient3',
        'provider_class': WebDAVProvider,
        'params': ['endpoint', 'access_key', 'secret_key'],
        'icon': 'webdav',
        'need_bucket': False,
        'need_region': False,
        'need_endpoint': True,
        'supports_bucket_cors': False,
        'supports_bucket_acl': False,
        'supports_multipart_management': False,
    },
    'onedrive': {
        'name': 'OneDrive',
        'protocol': 'onedrive',
        'sdk': 'msal',
        'provider_class': OneDriveProvider,
        'params': ['access_key', 'secret_key', 'extra_config'],
        'icon': 'onedrive',
        'need_bucket': False,
        'need_region': False,
        'need_endpoint': False,
        'supports_bucket_cors': False,
        'supports_bucket_acl': False,
        'supports_multipart_management': False,
    },
}


def get_provider(account):
    provider_info = PROVIDER_REGISTRY.get(account.provider)
    if not provider_info:
        raise ValueError("不支持的云存储厂商: {}".format(account.provider))
    provider_cls = provider_info['provider_class']
    return provider_cls(account)


def get_provider_info(provider_key):
    return PROVIDER_REGISTRY.get(provider_key)


def get_all_providers():
    result = []
    for key, info in PROVIDER_REGISTRY.items():
        result.append({
            'key': key,
            'name': info['name'],
            'protocol': info['protocol'],
            'sdk': info['sdk'],
            'params': info['params'],
            'icon': info.get('icon', ''),
            'need_bucket': info.get('need_bucket', True),
            'need_region': info.get('need_region', False),
            'need_endpoint': info.get('need_endpoint', False),
            'endpoint_template': info.get('endpoint_template', ''),
            'region_options': info.get('region_options', []),
            's3_path_style': info.get('s3_path_style', False),
            'supports_bucket_cors': info.get('supports_bucket_cors', False),
            'supports_bucket_acl': info.get('supports_bucket_acl', False),
            'supports_multipart_management': info.get('supports_multipart_management', False),
        })
    return result
