AI_TOOL_CONFIGS = [
    {
        'name': 'get_system_info',
        'display_name': '系统信息',
        'tool_type': 'system',
        'description': '获取服务器系统基本信息，包括主机名、操作系统、CPU、内存、磁盘使用情况、运行时间、系统负载等综合信息。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 1,
    },
    {
        'name': 'get_cpu_info',
        'display_name': 'CPU信息',
        'tool_type': 'system',
        'description': '获取CPU详细信息，包括每个核心的使用率、CPU频率、核心数等。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 2,
    },
    {
        'name': 'get_memory_info',
        'display_name': '内存信息',
        'tool_type': 'system',
        'description': '获取内存和交换分区使用详情，包括总量、已用、可用、使用率等。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 3,
    },
    {
        'name': 'get_disk_info',
        'display_name': '磁盘信息',
        'tool_type': 'system',
        'description': '获取磁盘分区和使用详情，包括每个分区的设备名、挂载点、文件系统类型、容量和使用率等。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 4,
    },
    {
        'name': 'get_network_info',
        'display_name': '网络信息',
        'tool_type': 'system',
        'description': '获取网络IO统计和当前网络连接列表，包括发送接收字节数、连接数、各连接状态等。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 5,
    },
    {
        'name': 'get_process_list',
        'display_name': '进程列表',
        'tool_type': 'system',
        'description': '获取系统进程列表，可按CPU或内存使用率排序。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 6,
    },
    {
        'name': 'execute_command',
        'display_name': '执行命令',
        'tool_type': 'system',
        'description': '在服务器上执行命令并返回结果。此为高危操作，仅用于系统诊断和管理。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 7,
    },
    {
        'name': 'get_system_logs',
        'display_name': '系统日志',
        'tool_type': 'system',
        'description': '获取系统日志内容，支持查看系统日志、认证日志、内核日志等。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 8,
    },
    {
        'name': 'list_directory',
        'display_name': '目录列表',
        'tool_type': 'file',
        'description': '列出指定目录下的文件和子目录，包括文件大小、权限、修改时间等信息。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 10,
    },
    {
        'name': 'read_file',
        'display_name': '读取文件',
        'tool_type': 'file',
        'description': '读取指定文件的内容，支持指定行范围。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 11,
    },
    {
        'name': 'write_file',
        'display_name': '写入文件',
        'tool_type': 'file',
        'description': '写入内容到指定文件。此为高危操作，会修改或创建文件。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 12,
    },
    {
        'name': 'search_files',
        'display_name': '搜索文件',
        'tool_type': 'file',
        'description': '在指定目录下搜索文件，支持通配符模式匹配。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 13,
    },
    {
        'name': 'search_in_file',
        'display_name': '文件内容搜索',
        'tool_type': 'file',
        'description': '在文件中搜索包含指定关键词的行。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 14,
    },
    {
        'name': 'get_service_status',
        'display_name': '服务状态',
        'tool_type': 'service',
        'description': '获取指定系统服务的运行状态，包括是否运行、PID、内存占用等。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 20,
    },
    {
        'name': 'list_services',
        'display_name': '服务列表',
        'tool_type': 'service',
        'description': '列出系统服务，可筛选运行中、已停止或全部服务。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 21,
    },
    {
        'name': 'manage_service',
        'display_name': '服务管理',
        'tool_type': 'service',
        'description': '管理系统服务，支持启动、停止、重启、重载等操作。此为高危操作。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 22,
    },
    {
        'name': 'get_service_logs',
        'display_name': '服务日志',
        'tool_type': 'service',
        'description': '获取指定服务的最近日志。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 23,
    },
    {
        'name': 'docker_list_containers',
        'display_name': '容器列表',
        'tool_type': 'docker',
        'description': '列出Docker容器，包括运行中和停止的容器。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 30,
    },
    {
        'name': 'docker_container_info',
        'display_name': '容器详情',
        'tool_type': 'docker',
        'description': '获取Docker容器的详细信息，包括配置、网络、挂载等。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 31,
    },
    {
        'name': 'docker_container_logs',
        'display_name': '容器日志',
        'tool_type': 'docker',
        'description': '获取Docker容器的日志。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 32,
    },
    {
        'name': 'docker_manage_container',
        'display_name': '容器管理',
        'tool_type': 'docker',
        'description': '管理Docker容器，支持启动、停止、重启、删除等操作。此为高危操作。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 33,
    },
    {
        'name': 'docker_list_images',
        'display_name': '镜像列表',
        'tool_type': 'docker',
        'description': '列出Docker镜像。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 34,
    },
    {
        'name': 'docker_stats',
        'display_name': '容器资源',
        'tool_type': 'docker',
        'description': '获取Docker容器的资源使用情况（CPU、内存、网络、磁盘IO）。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 35,
    },
    {
        'name': 'mysql_status',
        'display_name': 'MySQL状态',
        'tool_type': 'database',
        'description': '获取MySQL/MariaDB服务状态和基本运行信息。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 40,
    },
    {
        'name': 'mysql_execute',
        'display_name': 'MySQL查询',
        'tool_type': 'database',
        'description': '执行MySQL/MariaDB SQL查询语句。此为高危操作。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 41,
    },
    {
        'name': 'mysql_list_databases',
        'display_name': 'MySQL数据库列表',
        'tool_type': 'database',
        'description': '列出MySQL/MariaDB中的所有数据库。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 42,
    },
    {
        'name': 'redis_status',
        'display_name': 'Redis状态',
        'tool_type': 'database',
        'description': '获取Redis服务状态和基本运行信息。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 43,
    },
    {
        'name': 'redis_execute',
        'display_name': 'Redis命令',
        'tool_type': 'database',
        'description': '执行Redis命令。此为高危操作。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 44,
    },
    {
        'name': 'list_websites',
        'display_name': '网站列表',
        'tool_type': 'website',
        'description': '列出服务器上配置的网站，通过扫描Nginx/Apache配置文件获取。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 50,
    },
    {
        'name': 'get_website_config',
        'display_name': '网站配置',
        'tool_type': 'website',
        'description': '读取网站配置文件内容。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 51,
    },
    {
        'name': 'check_website_status',
        'display_name': '网站状态',
        'tool_type': 'website',
        'description': '检查网站是否可以正常访问，返回HTTP状态码和响应时间。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 52,
    },
    {
        'name': 'get_nginx_status',
        'display_name': 'Nginx状态',
        'tool_type': 'website',
        'description': '获取Nginx服务状态和配置信息。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 53,
    },
    {
        'name': 'reload_nginx',
        'display_name': '重载Nginx',
        'tool_type': 'website',
        'description': '重载Nginx配置，使配置变更生效而不中断服务。此为高危操作。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 54,
    },
    {
        'name': 'restart_nginx',
        'display_name': '重启Nginx',
        'tool_type': 'website',
        'description': '重启Nginx服务。此为高危操作。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 55,
    },
    {
        'name': 'get_firewall_status',
        'display_name': '防火墙状态',
        'tool_type': 'security',
        'description': '获取防火墙状态和规则列表。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 60,
    },
    {
        'name': 'get_ssh_config',
        'display_name': 'SSH配置',
        'tool_type': 'security',
        'description': '获取SSH服务配置信息，包括端口、认证方式、root登录等安全设置。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 61,
    },
    {
        'name': 'get_login_history',
        'display_name': '登录历史',
        'tool_type': 'security',
        'description': '获取系统登录历史记录，包括成功和失败的登录尝试。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 62,
    },
    {
        'name': 'get_open_ports',
        'display_name': '开放端口',
        'tool_type': 'security',
        'description': '获取服务器上开放的端口和对应的进程信息。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 63,
    },
    {
        'name': 'get_security_updates',
        'display_name': '安全更新',
        'tool_type': 'security',
        'description': '检查系统中可用的安全更新。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 64,
    },
    {
        'name': 'manage_firewall_rule',
        'display_name': '防火墙规则管理',
        'tool_type': 'security',
        'description': '管理防火墙规则，支持添加和删除规则。此为高危操作。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 65,
    },
    {
        'name': 'TodoRead',
        'display_name': '读取待办',
        'tool_type': 'command',
        'description': '读取当前会话的待办任务列表。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 70,
    },
    {
        'name': 'TodoWrite',
        'display_name': '写入待办',
        'tool_type': 'command',
        'description': '创建和管理结构化的任务列表，帮助跟踪进度和组织复杂任务。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 71,
    },
    {
        'name': 'panel_shop_list',
        'display_name': '应用商店列表',
        'tool_type': 'panel',
        'description': '获取如意面板应用商店的软件列表，包含安装状态和可用版本。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 80,
    },
    {
        'name': 'panel_shop_install',
        'display_name': '安装应用',
        'tool_type': 'panel',
        'description': '从如意面板应用商店安装软件，安装过程异步执行。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 81,
    },
    {
        'name': 'panel_shop_manage',
        'display_name': '应用管理',
        'tool_type': 'panel',
        'description': '管理应用商店中已安装的软件，支持启动、停止、重启、卸载等操作。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 82,
    },
    {
        'name': 'panel_shop_task_status',
        'display_name': '安装任务状态',
        'tool_type': 'panel',
        'description': '查询应用商店的安装任务状态和进度。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 83,
    },
    {
        'name': 'panel_docker_square_list',
        'display_name': 'Docker广场应用列表',
        'tool_type': 'panel',
        'description': '获取Docker广场中已安装的应用列表及状态。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 84,
    },
    {
        'name': 'panel_docker_square_catalog',
        'display_name': 'Docker广场应用目录',
        'tool_type': 'panel',
        'description': '获取Docker广场中可安装的应用目录。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 85,
    },
    {
        'name': 'panel_docker_square_install',
        'display_name': '安装Docker广场应用',
        'tool_type': 'panel',
        'description': '从Docker广场一键安装应用，会创建Docker容器。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 86,
    },
    {
        'name': 'panel_docker_square_manage',
        'display_name': '管理Docker广场应用',
        'tool_type': 'panel',
        'description': '管理Docker广场中已安装的应用，支持启动、停止、重启、删除等操作。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 87,
    },
    {
        'name': 'panel_site_list',
        'display_name': '网站列表',
        'tool_type': 'panel',
        'description': '获取如意面板管理的网站站点列表。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 88,
    },
    {
        'name': 'panel_site_create',
        'display_name': '创建网站',
        'tool_type': 'panel',
        'description': '在如意面板中创建网站站点，会修改Web服务器配置。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 89,
    },
    {
        'name': 'panel_site_manage',
        'display_name': '网站管理',
        'tool_type': 'panel',
        'description': '管理网站站点，支持启动、停止、删除等操作。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 90,
    },
    {
        'name': 'panel_site_domains',
        'display_name': '网站域名管理',
        'tool_type': 'panel',
        'description': '管理网站站点的域名绑定，添加或删除域名。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 91,
    },
    {
        'name': 'panel_runtime_site_create',
        'display_name': '创建运行时项目站点',
        'tool_type': 'panel',
        'description': '创建Python/Node/Go/PHP运行时项目站点，配置运行环境。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 91,
    },
    {
        'name': 'panel_site_ssl',
        'display_name': '网站SSL管理',
        'tool_type': 'panel',
        'description': '管理网站SSL证书，申请、启用、关闭SSL等。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 91,
    },
    {
        'name': 'panel_site_proxy',
        'display_name': '网站反向代理管理',
        'tool_type': 'panel',
        'description': '管理网站反向代理配置，添加或删除反向代理。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 91,
    },
    {
        'name': 'panel_deploy_project',
        'display_name': '一键部署项目',
        'tool_type': 'panel',
        'description': '一键部署Python/Node/Go/PHP项目，自动创建运行时站点、Nginx静态站点、反向代理和SSL。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 91,
    },
    {
        'name': 'panel_database_list',
        'display_name': '数据库列表',
        'tool_type': 'panel',
        'description': '获取如意面板管理的数据库列表。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 92,
    },
    {
        'name': 'panel_database_create',
        'display_name': '创建数据库',
        'tool_type': 'panel',
        'description': '在如意面板中创建数据库和用户。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 93,
    },
    {
        'name': 'panel_database_delete',
        'display_name': '删除数据库',
        'tool_type': 'panel',
        'description': '删除如意面板中的数据库，数据不可恢复。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 94,
    },
    {
        'name': 'panel_database_reset_pass',
        'display_name': '重置数据库密码',
        'tool_type': 'panel',
        'description': '重置数据库用户的密码。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 95,
    },
    {
        'name': 'panel_database_root_pass',
        'display_name': '获取数据库Root密码',
        'tool_type': 'panel',
        'description': '获取数据库管理员Root密码。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 96,
    },
    {
        'name': 'crontab_list',
        'display_name': '定时任务列表',
        'tool_type': 'panel',
        'description': '获取服务器定时任务列表。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 97,
    },
    {
        'name': 'crontab_create',
        'display_name': '创建定时任务',
        'tool_type': 'panel',
        'description': '创建新的定时任务，可设置执行周期和Shell脚本。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 98,
    },
    {
        'name': 'crontab_delete',
        'display_name': '删除定时任务',
        'tool_type': 'panel',
        'description': '删除指定的定时任务。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 99,
    },
    {
        'name': 'crontab_toggle',
        'display_name': '启停定时任务',
        'tool_type': 'panel',
        'description': '启用或停用定时任务。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 100,
    },
    {
        'name': 'crontab_run',
        'display_name': '立即执行定时任务',
        'tool_type': 'panel',
        'description': '立即执行一次指定的定时任务。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 101,
    },
    {
        'name': 'crontab_logs',
        'display_name': '定时任务日志',
        'tool_type': 'panel',
        'description': '获取定时任务的执行日志。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 102,
    },
    {
        'name': 'crontab_create_ai',
        'display_name': '创建AI定时任务',
        'tool_type': 'panel',
        'description': '创建AI增强型定时任务，AI自动执行提示词描述的任务并投递结果到通知渠道。支持静默模式、任务链、一次性定时等。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 103,
    },
    {
        'name': 'crontab_ai_result',
        'display_name': 'AI任务最近结果',
        'tool_type': 'panel',
        'description': '获取AI定时任务的最近一次执行结果。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 104,
    },
    {
        'name': 'alert_list',
        'display_name': '告警任务列表',
        'tool_type': 'panel',
        'description': '获取告警任务列表，查看系统资源监控、网站监控、SSL过期等告警规则。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 110,
    },
    {
        'name': 'alert_create',
        'display_name': '创建告警任务',
        'tool_type': 'panel',
        'description': '创建告警任务，支持CPU/内存/磁盘/网络/SSL/网站监控等告警类型。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 111,
    },
    {
        'name': 'alert_toggle',
        'display_name': '启停告警任务',
        'tool_type': 'panel',
        'description': '启用或停用告警任务。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 112,
    },
    {
        'name': 'alert_delete',
        'display_name': '删除告警任务',
        'tool_type': 'panel',
        'description': '删除指定的告警任务。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 113,
    },
    {
        'name': 'alert_test',
        'display_name': '测试告警通知',
        'tool_type': 'panel',
        'description': '测试告警任务的通知渠道是否正常，发送测试消息。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 114,
    },
    {
        'name': 'notify_channel_list',
        'display_name': '通知渠道列表',
        'tool_type': 'panel',
        'description': '获取告警通知渠道列表，查看邮件/钉钉/飞书/企微/Webhook等渠道配置。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 115,
    },
    {
        'name': 'notify_channel_test',
        'display_name': '测试通知渠道',
        'tool_type': 'panel',
        'description': '测试指定通知渠道是否正常，发送测试消息验证配置。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 116,
    },
    {
        'name': 'agent_call',
        'display_name': '调用智能体',
        'tool_type': 'agent',
        'description': '调用其他智能体完成复杂任务，支持多智能体协作。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 117,
    },
    {
        'name': 'request_user_input',
        'display_name': '请求用户输入',
        'tool_type': 'agent',
        'description': '向用户请求输入信息，用于需要用户确认或补充参数的场景。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 118,
    },
    {
        'name': 'start_command',
        'display_name': '启动后台命令',
        'tool_type': 'system',
        'description': '在后台启动长时间运行的命令，返回命令ID用于后续查询状态。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 119,
    },
    {
        'name': 'stop_command',
        'display_name': '终止后台命令',
        'tool_type': 'system',
        'description': '终止正在运行的后台命令。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 120,
    },
    {
        'name': 'check_command_status',
        'display_name': '查询命令状态',
        'tool_type': 'system',
        'description': '查询后台命令的执行状态和输出。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 121,
    },
    {
        'name': 'search_docs',
        'display_name': '搜索面板文档',
        'tool_type': 'system',
        'description': '搜索如意面板的使用文档和帮助信息。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 122,
    },
    {
        'name': 'list_docs',
        'display_name': '列出面板文档',
        'tool_type': 'system',
        'description': '列出如意面板所有可用的文档目录。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 123,
    },
    {
        'name': 'web_search',
        'display_name': '网络搜索',
        'tool_type': 'system',
        'description': '搜索互联网获取最新信息，用于需要实时数据的场景。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 124,
    },
    {
        'name': 'security_scan',
        'display_name': '安全风险扫描',
        'tool_type': 'security',
        'description': '扫描服务器安全风险，检查配置漏洞和潜在威胁。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 125,
    },
    {
        'name': 'security_scan_result',
        'display_name': '安全扫描结果',
        'tool_type': 'security',
        'description': '获取安全风险扫描的结果详情。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 126,
    },
    {
        'name': 'vuln_scan_kernel',
        'display_name': '内核漏洞扫描',
        'tool_type': 'vulnerability',
        'description': '扫描Linux内核已知漏洞（CVE），检查当前内核版本是否存在安全漏洞。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 127,
    },
    {
        'name': 'vuln_get_cve_info',
        'display_name': 'CVE漏洞详情',
        'tool_type': 'vulnerability',
        'description': '获取指定CVE漏洞的详细信息，包括影响版本和修复建议。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 128,
    },
    {
        'name': 'vuln_scan_packages',
        'display_name': '软件包漏洞扫描',
        'tool_type': 'vulnerability',
        'description': '扫描已安装软件包的已知漏洞，检查是否有安全更新可用。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 129,
    },
    {
        'name': 'waf_get_status',
        'display_name': 'WAF状态',
        'tool_type': 'waf',
        'description': '获取Web应用防火墙(WAF)的运行状态和模式。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 130,
    },
    {
        'name': 'waf_set_status',
        'display_name': 'WAF模式切换',
        'tool_type': 'waf',
        'description': '切换WAF防火墙的运行模式（检测/拦截/关闭）。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 131,
    },
    {
        'name': 'waf_get_dashboard',
        'display_name': 'WAF仪表盘',
        'tool_type': 'waf',
        'description': '获取WAF防火墙的仪表盘数据，包括攻击统计和趋势。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 132,
    },
    {
        'name': 'waf_get_attack_logs',
        'display_name': 'WAF攻击日志',
        'tool_type': 'waf',
        'description': '获取WAF防火墙的攻击日志记录。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 133,
    },
    {
        'name': 'waf_manage_ip',
        'display_name': 'WAF IP管理',
        'tool_type': 'waf',
        'description': '管理WAF防火墙的IP黑白名单，添加或删除IP规则。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 134,
    },
    {
        'name': 'waf_manage_rule',
        'display_name': 'WAF规则管理',
        'tool_type': 'waf',
        'description': '管理WAF防火墙的防护规则，添加或删除规则。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 135,
    },
    {
        'name': 'waf_manage_url_rule',
        'display_name': 'WAF URL规则管理',
        'tool_type': 'waf',
        'description': '管理WAF防火墙的URL防护规则，添加或删除URL规则。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 136,
    },
    {
        'name': 'waf_get_site_config',
        'display_name': 'WAF站点配置',
        'tool_type': 'waf',
        'description': '获取WAF防火墙的站点防护配置。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 137,
    },
    {
        'name': 'waf_set_site_status',
        'display_name': 'WAF站点模式切换',
        'tool_type': 'waf',
        'description': '切换WAF防火墙的站点防护模式。',
        'is_enabled': True,
        'is_dangerous': True,
        'require_confirm': True,
        'sort_order': 138,
    },
    {
        'name': 'waf_ip_attack_analysis',
        'display_name': 'WAF IP攻击分析',
        'tool_type': 'waf',
        'description': '分析指定IP的WAF攻击记录，统计攻击类型和频率。',
        'is_enabled': True,
        'is_dangerous': False,
        'require_confirm': False,
        'sort_order': 139,
    },
]

AI_SYS_CONFIG = {
    'system_prompt': '',
    'max_turns': 100,
    'max_context_messages': 20,
    'enable_web_search': False,
    'enable_context_compress': True,
    'context_compress_threshold': 10000,
    'require_command_confirm': 'medium_high',
    'show_assistant': True,
}


def init_ai_tool_config(force=False):
    from apps.sysai.models import AIToolConfig

    if force:
        AIToolConfig.objects.filter(
            name__in=[cfg['name'] for cfg in AI_TOOL_CONFIGS]
        ).delete()

    created_count = 0
    skipped_count = 0

    for config_data in AI_TOOL_CONFIGS:
        tool_name = config_data.get('name')
        defaults = {k: v for k, v in config_data.items()}

        obj, created = AIToolConfig.objects.get_or_create(
            name=tool_name,
            defaults=defaults,
        )

        if created:
            created_count += 1
        else:
            skipped_count += 1
            update_fields = []
            for key, value in defaults.items():
                if key == 'name':
                    continue
                if getattr(obj, key, None) != value:
                    setattr(obj, key, value)
                    update_fields.append(key)
            if update_fields:
                obj.save(update_fields=update_fields)
                created_count += 1

    return created_count, skipped_count


def init_ai_sys_config(force=False):
    from apps.sysai.models import AIModel

    config_obj, created = AIModel.objects_all.get_or_create(
        name='__sys_config__',
        defaults={
            'model_name': '__sys_config__',
            'provider': 'custom',
            'extra_params': AI_SYS_CONFIG,
        },
    )

    if not created and force:
        config_obj.extra_params = AI_SYS_CONFIG
        config_obj.save(update_fields=['extra_params'])
        return True

    return created


def init_ai_data(force=False):
    tool_created, tool_skipped = init_ai_tool_config(force=force)
    config_created = init_ai_sys_config(force=force)
    return tool_created, tool_skipped, config_created
