# Generated by Django 5.0.3 on 2024-11-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_apscheduler', '0009_djangojobexecution_unique_job_executions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('is_sys', models.BooleanField(default=False, verbose_name='是否系统任务')),
                ('status', models.BooleanField(default=True, verbose_name='任务状态')),
                ('period_type', models.SmallIntegerField(choices=[(0, ''), (1, '每天'), (2, '每周'), (3, '每月'), (4, '每小时'), (5, '每隔N天'), (6, '每隔N时'), (7, '每隔N分'), (8, '每隔N秒')], default=0, verbose_name='周期类型')),
                ('year', models.IntegerField(default=0, verbose_name='年')),
                ('month', models.IntegerField(default=0, verbose_name='月')),
                ('week', models.IntegerField(default=0, verbose_name='周')),
                ('day', models.IntegerField(default=0, verbose_name='天')),
                ('hour', models.IntegerField(default=0, verbose_name='小时')),
                ('minute', models.IntegerField(default=0, verbose_name='分钟')),
                ('second', models.IntegerField(default=0, verbose_name='秒')),
                ('shell_body', models.TextField(blank=True, null=True, verbose_name='执行shell内容')),
                ('type', models.SmallIntegerField(choices=[(0, 'shell'), (1, 'bk_database'), (2, 'bk_website'), (3, 'bk_dir'), (4, 'access_url')], default=0, verbose_name='类型')),
                ('database', models.TextField(blank=True, null=True, verbose_name='备份数据库')),
                ('website', models.TextField(blank=True, null=True, verbose_name='备份网站')),
                ('dir', models.TextField(blank=True, null=True, verbose_name='备份目录')),
                ('exclude_rules', models.TextField(blank=True, null=True, verbose_name='备份目录排除规则')),
                ('url', models.TextField(blank=True, null=True, verbose_name='url内容')),
                ('db_type', models.SmallIntegerField(choices=[(0, 'mysql')], default=0, verbose_name='备份数据库类型')),
                ('backup_to', models.SmallIntegerField(choices=[(0, ''), (1, 'local')], default=0, verbose_name='备份到目标')),
                ('saveNums', models.IntegerField(default=0, verbose_name='保留份数')),
                ('job', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_apscheduler.djangojob', verbose_name='关联DjangoJob')),
            ],
            options={
                'verbose_name': '定时任务表',
                'verbose_name_plural': '定时任务表',
                'db_table': 'ruyi_crontab_task',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='SysTaskCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='任务名称')),
                ('type', models.SmallIntegerField(choices=[(0, '安装软件'), (1, '其他')], default=0, verbose_name='类型')),
                ('log', models.TextField(blank=True, null=True, verbose_name='日志名称（filename）')),
                ('status', models.SmallIntegerField(choices=[(0, '待处理'), (1, '进行中'), (2, '已失败'), (3, '已完成')], default=0, verbose_name='任务状态')),
                ('duration', models.IntegerField(default=0, verbose_name='耗时(秒)')),
                ('func_path', models.TextField(blank=True, null=True)),
                ('params', models.TextField(blank=True, null=True)),
                ('exec_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('job', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_apscheduler.djangojob', verbose_name='关联DjangoJob')),
            ],
            options={
                'verbose_name': '系统任务中心',
                'verbose_name_plural': '系统任务中心',
                'db_table': 'ruyi_systask_center',
                'ordering': ('-create_at',),
            },
        ),
    ]
