services:
  RUYI_DKAPP:
    image: wordpress:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPU}
          memory: ${MEM}
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: 0
    ports:
      - ${HOST_IP}:${WORDPRESS_PORT}:80
    volumes:
      - ${APP_PATH}/html:/var/www/html
      - ${APP_PATH}/ry_config.ini:/usr/local/etc/php/conf.d/ry_config.ini
    labels:
      createdBy: "ruyi_apps"
    networks:
      - ruyi-network

networks:
  ruyi-network:
    external: true