# Generated by Django 5.0.3 on 2024-11-15 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_apscheduler', '0009_djangojobexecution_unique_job_executions'),
        ('systask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuyiBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件名称')),
                ('filename', models.TextField(blank=True, null=True, verbose_name='绝对路径名称')),
                ('size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('fid', models.CharField(blank=True, max_length=255, null=True, verbose_name='关联id')),
                ('type', models.CharField(blank=True, choices=[(1, '数据库备份'), (2, '网站备份'), (3, '目录备份')], max_length=255, null=True, verbose_name='类型')),
                ('store_type', models.CharField(blank=True, choices=[('local', '本地'), ('remote', '远程')], default='local', max_length=255, null=True, verbose_name='存储')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('cron', models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systask.crontabtask', verbose_name='关联计划任务')),
                ('job', models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_apscheduler.djangojob', verbose_name='关联job')),
            ],
            options={
                'verbose_name': '备份列表',
                'verbose_name_plural': '备份列表',
                'db_table': 'ruyi_backup',
                'ordering': ('-create_at',),
            },
        ),
    ]
