# Generated by Django 5.1.7 on 2025-03-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysbak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruyibackup',
            name='type',
            field=models.CharField(blank=True, choices=[(1, '数据库备份'), (2, '网站备份'), (3, '目录备份'), (4, '应用备份')], max_length=255, null=True, verbose_name='类型'),
        ),
    ]
