from . import system
from . import file
from . import service
from . import docker
from . import database
from . import website
from . import security
from . import vulnerability
from . import waf
from . import agent_tools
from . import panel_shop
from . import panel_docker
from . import panel_website
from . import panel_database
from . import panel_env
from . import panel_detect
from . import web_search
from . import knowledge
from . import crontab
from . import alert

from apps.sysai.skills import skill_tool
from apps.sysai.skills import skill_manage_tool
