# Generated by Django 5.0.3 on 2024-11-15 12:32

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='用户账号')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='邮箱')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='电话')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否员工')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否超级管理员')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'ruyi_users',
                'ordering': ('-create_at',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CertManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='域名')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='证书目录')),
                ('endTime', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('info', models.TextField(blank=True, default=dict, null=True, verbose_name='证书信息')),
                ('store_type', models.CharField(blank=True, choices=[('local', '本地'), ('remote', '远程')], default='local', max_length=255, null=True, verbose_name='存储')),
            ],
            options={
                'verbose_name': '证书管理',
                'verbose_name_plural': '证书管理',
                'db_table': 'ruyi_cert',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='CommonCommands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='命令名称')),
                ('shell', models.TextField(blank=True, null=True, verbose_name='常用命令')),
            ],
            options={
                'verbose_name': '常用命令',
                'verbose_name_plural': '常用命令',
                'db_table': 'ruyi_common_commands',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(blank=True, default=dict, null=True, verbose_name='面板配置')),
                ('mysql_root', models.CharField(blank=True, max_length=100, null=True, verbose_name='mysql的root密码')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
                'db_table': 'ruyi_config',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('db_host', models.CharField(blank=True, max_length=255, null=True, verbose_name='服务器地址')),
                ('db_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='数据库名')),
                ('db_port', models.IntegerField(default=0, verbose_name='数据库端口')),
                ('format', models.CharField(blank=True, max_length=60, null=True, verbose_name='数据库编码')),
                ('db_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
                ('db_pass', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('accept', models.CharField(blank=True, choices=[('all', '所有人'), ('localhost', '本地服务器'), ('ip', '指定IP')], max_length=255, null=True, verbose_name='访问权限')),
                ('accept_ips', models.TextField(blank=True, null=True, verbose_name='允许的多个ip（逗号分割）')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('db_type', models.IntegerField(choices=[(0, 'MySQL'), (1, 'SqlServer'), (2, 'MongoDB'), (3, 'PgSql'), (4, 'Redis')], default=0, verbose_name='数据库类型')),
                ('is_remote', models.BooleanField(default=False, verbose_name='是否远程数据库')),
            ],
            options={
                'verbose_name': '数据库表',
                'verbose_name_plural': '数据库表',
                'db_table': 'ruyi_databases',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='分组名')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认分组')),
            ],
            options={
                'verbose_name': '站点分组',
                'verbose_name_plural': '站点分组',
                'db_table': 'ruyi_sites_group',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='TerminalServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('host', models.CharField(max_length=100, verbose_name='服务器IP/域名')),
                ('port', models.IntegerField(default=22, help_text='端口号', verbose_name='端口号')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='密码')),
                ('pkey', models.CharField(blank=True, max_length=255, null=True, verbose_name='私钥')),
                ('pkey_passwd', models.CharField(blank=True, max_length=255, null=True, verbose_name='私钥密码')),
                ('type', models.SmallIntegerField(choices=[(0, '密码验证'), (1, '私钥验证')], default=0, help_text='验证方式', verbose_name='验证方式')),
            ],
            options={
                'verbose_name': '终端服务器列表',
                'verbose_name_plural': '终端服务器列表',
                'db_table': 'ruyi_terminal',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='站点名')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='站点根目录')),
                ('status', models.BooleanField(default=True, verbose_name='站点状态')),
                ('type', models.IntegerField(choices=[(0, 'Static'), (1, 'Python'), (2, 'Node'), (3, 'Php'), (4, 'Go')], default=0, verbose_name='类型')),
                ('sslcfg', models.TextField(blank=True, default=dict, null=True, verbose_name='SSL配置')),
                ('wafcfg', models.TextField(blank=True, default=dict, null=True, verbose_name='WAF配置')),
                ('endTime', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认站点')),
                ('access_log', models.BooleanField(default=True, verbose_name='启用访问日志')),
                ('error_log', models.BooleanField(default=True, verbose_name='启用错误日志')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sitegroup', verbose_name='所属分组')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'db_table': 'ruyi_sites',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='域名')),
                ('port', models.IntegerField(default=0, verbose_name='端口')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sites', verbose_name='所属网站')),
            ],
            options={
                'verbose_name': '站点域名',
                'verbose_name_plural': '站点域名',
                'db_table': 'ruyi_site_domains',
                'ordering': ('-create_at',),
            },
        ),
    ]
