# Generated by Django 5.0.3 on 2024-11-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='project_cfg',
            field=models.TextField(blank=True, default=dict, null=True, verbose_name='项目配置'),
        ),
    ]
