# Generated by Django 6.0.1 on 2026-02-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_sites_project_cfg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminalserver',
            name='pkey',
            field=models.TextField(blank=True, null=True, verbose_name='私钥'),
        ),
    ]
