# Generated by Django 4.1 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_terminalserver_pkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalserver',
            name='connect_protocol',
            field=models.CharField(choices=[('ssh', 'SSH'), ('rdp', 'RDP')], default='ssh', max_length=20, verbose_name='连接协议'),
        ),
        migrations.AddField(
            model_name='terminalserver',
            name='rdp_color_depth',
            field=models.IntegerField(default=32, verbose_name='RDP 色深'),
        ),
        migrations.AddField(
            model_name='terminalserver',
            name='rdp_domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RDP 域'),
        ),
        migrations.AddField(
            model_name='terminalserver',
            name='rdp_ignore_cert',
            field=models.BooleanField(default=True, verbose_name='RDP 忽略证书'),
        ),
        migrations.AddField(
            model_name='terminalserver',
            name='rdp_security',
            field=models.CharField(blank=True, choices=[('', '默认'), ('any', '自动'), ('nla', 'NLA'), ('tls', 'TLS'), ('rdp', 'RDP')], default='', max_length=20, null=True, verbose_name='RDP 安全模式'),
        ),
    ]
