# Generated by Django 6.0.1 on 2026-05-07 10:44

import django.db.models.deletion
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('model_name', models.CharField(max_length=200, verbose_name='模型标识')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini'), ('zhipu', '智谱AI'), ('baidu', '百度文心'), ('alibaba', '阿里通义'), ('custom', '自定义')], db_index=True, max_length=50, verbose_name='厂商')),
                ('model_type', models.CharField(choices=[('LLM', '大语言模型'), ('EMBEDDING', '嵌入模型'), ('TTS', '语音合成'), ('STT', '语音识别'), ('IMAGE', '图像模型')], default='LLM', max_length=50, verbose_name='模型类型')),
                ('api_base', models.CharField(blank=True, default='', max_length=500, verbose_name='API地址')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='API密钥')),
                ('api_secret', models.CharField(blank=True, default='', max_length=500, verbose_name='API Secret')),
                ('api_version', models.CharField(blank=True, default='', max_length=50, verbose_name='API版本')),
                ('max_tokens', models.IntegerField(default=4096, verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('top_p', models.FloatField(default=1.0, verbose_name='Top P')),
                ('extra_params', models.JSONField(default=dict, verbose_name='额外参数')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': 'AI模型',
                'verbose_name_plural': 'AI模型',
                'db_table': 'ruyi_ai_model',
                'ordering': ['sort_order', '-create_at'],
            },
        ),
        migrations.CreateModel(
            name='AIToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='工具名称')),
                ('display_name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('tool_type', models.CharField(choices=[('system', '系统监控'), ('file', '文件管理'), ('service', '服务管理'), ('docker', '容器管理'), ('database', '数据库管理'), ('website', '网站管理'), ('security', '安全管理'), ('command', '命令执行'), ('custom', '自定义')], max_length=50, verbose_name='工具类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='工具描述')),
                ('parameters_schema', models.JSONField(default=dict, verbose_name='参数定义')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='是否危险操作')),
                ('require_confirm', models.BooleanField(default=False, verbose_name='是否需要确认')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': 'AI工具配置',
                'verbose_name_plural': 'AI工具配置',
                'db_table': 'ruyi_ai_tool_config',
                'ordering': ['sort_order', 'tool_type'],
            },
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('id', models.CharField(default=utils.models.make_uuid, max_length=64, primary_key=True, serialize=False, verbose_name='会话ID')),
                ('title', models.CharField(default='新对话', max_length=200, verbose_name='会话标题')),
                ('message_count', models.IntegerField(default=0, verbose_name='消息数量')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token数')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysai.aimodel', verbose_name='使用模型')),
            ],
            options={
                'verbose_name': 'AI会话',
                'verbose_name_plural': 'AI会话',
                'db_table': 'ruyi_ai_chat_session',
                'ordering': ['-is_pinned', '-update_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('id', models.CharField(default=utils.models.make_uuid, max_length=64, primary_key=True, serialize=False, verbose_name='消息ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手'), ('system', '系统'), ('tool', '工具')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('reasoning_content', models.TextField(blank=True, default='', verbose_name='思考内容')),
                ('tool_calls', models.JSONField(default=list, verbose_name='工具调用')),
                ('tool_call_id', models.CharField(blank=True, default='', max_length=100, verbose_name='工具调用ID')),
                ('tool_name', models.CharField(blank=True, default='', max_length=100, verbose_name='工具名称')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='消耗Token')),
                ('is_stop', models.BooleanField(default=False, verbose_name='是否已停止')),
                ('is_error', models.BooleanField(default=False, verbose_name='是否出错')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sysai.aichatsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': 'AI消息',
                'verbose_name_plural': 'AI消息',
                'db_table': 'ruyi_ai_chat_message',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入Token')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出Token')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='费用')),
                ('model_name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('provider', models.CharField(max_length=50, verbose_name='厂商')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysai.aimodel', verbose_name='使用模型')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysai.aichatsession', verbose_name='会话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI用量日志',
                'verbose_name_plural': 'AI用量日志',
                'db_table': 'ruyi_ai_usage_log',
                'ordering': ['-create_at'],
            },
        ),
    ]
