# Generated by Django 6.0.1 on 2026-05-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='aiusagelog',
            name='user',
        ),
        migrations.AddField(
            model_name='aichatsession',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户ID'),
        ),
    ]
