# Generated by Django 6.0.1 on 2026-05-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysai', '0002_remove_aichatsession_user_remove_aiusagelog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama'), ('longcat', 'Longcat'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Gemini'), ('zhipu', '智谱AI'), ('baidu', '百度文心'), ('alibaba', '阿里通义'), ('custom', '自定义')], db_index=True, max_length=50, verbose_name='厂商'),
        ),
    ]
