# Generated by Django 6.0.1 on 2026-05-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysai', '0003_add_longcat_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='session_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='会话标题'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='max_tokens',
            field=models.IntegerField(default=8192, verbose_name='最大Token数'),
        ),
    ]
