# Generated by Django 6.0.1 on 2026-05-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysai', '0004_add_session_title_to_aiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatsession',
            name='agent_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='智能体ID'),
        ),
    ]
