# Generated by Django 6.0.1 on 2026-05-10 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysai', '0005_add_agent_id_to_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICompactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('summary', models.TextField(verbose_name='压缩摘要')),
                ('compacted_count', models.IntegerField(default=0, verbose_name='压缩消息数')),
                ('flushed_facts', models.IntegerField(default=0, verbose_name='刷新事实数')),
                ('tokens_before', models.IntegerField(default=0, verbose_name='压缩前Token')),
                ('tokens_after', models.IntegerField(default=0, verbose_name='压缩后Token')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysai.aichatsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': 'AI压缩日志',
                'verbose_name_plural': 'AI压缩日志',
                'db_table': 'ruyi_ai_compaction_log',
                'ordering': ['-create_at'],
            },
        ),
    ]
