# Generated by Django 6.0.1 on 2026-05-10 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysai', '0006_aicompactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('content_text', models.TextField(verbose_name='原始文本')),
                ('embedding', models.BinaryField(verbose_name='向量数据')),
                ('embedding_model', models.CharField(blank=True, default='', max_length=128, verbose_name='嵌入模型')),
                ('source', models.CharField(default='memory', max_length=32, verbose_name='来源')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='内容哈希')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysai.aichatsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': 'AI向量嵌入',
                'verbose_name_plural': 'AI向量嵌入',
                'db_table': 'ruyi_ai_embedding',
                'indexes': [models.Index(fields=['session'], name='ruyi_ai_emb_session_bda0dd_idx'), models.Index(fields=['content_hash'], name='ruyi_ai_emb_content_e3fa94_idx')],
            },
        ),
    ]
