# Generated by Django 6.0.1 on 2026-05-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysai', '0007_aiembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='stop_reason',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='停止原因'),
        ),
    ]
