# Generated by Django 6.0.1 on 2026-05-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysai', '0008_add_stop_reason_to_aichatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitoolconfig',
            name='tool_type',
            field=models.CharField(choices=[('system', '系统监控'), ('file', '文件管理'), ('service', '服务管理'), ('docker', '容器管理'), ('database', '数据库管理'), ('website', '网站管理'), ('security', '安全管理'), ('command', '命令执行'), ('panel', '面板集成'), ('custom', '自定义')], max_length=50, verbose_name='工具类型'),
        ),
    ]
