# Generated by Django 6.0.1 on 2026-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysai', '0009_alter_aitoolconfig_tool_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='max_tokens',
            field=models.IntegerField(default=4096, verbose_name='最大输出Token数'),
        ),
    ]
