# Generated by Django 6.0.1 on 2026-05-16 12:24

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysai', '0011_add_vllm_openrouter_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimodel',
            options={'base_manager_name': 'objects_all', 'ordering': ['sort_order', '-create_at'], 'verbose_name': 'AI模型', 'verbose_name_plural': 'AI模型'},
        ),
        migrations.AlterModelManagers(
            name='aimodel',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('objects_all', django.db.models.manager.Manager()),
            ],
        ),
    ]
