# Generated by Django 5.0.3 on 2024-11-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RySoftShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=100, verbose_name='软件名')),
                ('install_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='安装路径')),
                ('install_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='安装版本')),
                ('installed', models.BooleanField(default=False, verbose_name='是否安装')),
                ('status', models.SmallIntegerField(choices=[(0, '未安装'), (1, '已启动'), (2, '已停止')], default=0, verbose_name='状态')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='软件密码')),
                ('type', models.SmallIntegerField(choices=[(0, '未分类'), (2, '数据库'), (3, 'Web服务器'), (4, '运行环境'), (5, '安全防护')], default=0, verbose_name='分类')),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '软件列表',
                'verbose_name_plural': '软件列表',
                'db_table': 'ruyi_shop',
                'ordering': ('-create_at',),
            },
        ),
    ]
