# Generated by Django 5.0.3 on 2024-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rysoftshop',
            name='is_default',
            field=models.BooleanField(default=True, verbose_name='是否默认'),
        ),
    ]
