services:
  RUYI_DKAPP:
    image: dpage/pgadmin4:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPU}
          memory: ${MEM}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${HOST_IP}:${PGADMIN_PORT}:80
    volumes:
      - ${APP_PATH}/data:/var/lib/pgadmin
    labels:
      createdBy: "ruyi_apps"
    networks:
      - ruyi-network

networks:
  ruyi-network:
    external: true
