# Generated by Django 6.0.1 on 2026-02-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=50, verbose_name='渠道名称')),
                ('channel_type', models.CharField(choices=[('email', '邮件'), ('dingtalk', '钉钉'), ('feishu', '飞书'), ('wechat', '企业微信'), ('sms', '短信'), ('webhook', 'Webhook')], max_length=20, verbose_name='渠道类型')),
                ('config', models.TextField(default='{}', verbose_name='配置JSON')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('daily_limit', models.IntegerField(default=3, verbose_name='每日发送上限')),
                ('send_start_time', models.TimeField(default='00:00', verbose_name='允许发送开始时间')),
                ('send_end_time', models.TimeField(default='23:59', verbose_name='允许发送结束时间')),
                ('icon_type', models.CharField(choices=[('icon', 'Element Plus 图标'), ('image', '图片')], default='icon', max_length=10, verbose_name='图标类型')),
                ('icon', models.CharField(default='', max_length=100, verbose_name='图标名称或图片路径')),
                ('icon_color', models.CharField(default='#409eff', max_length=20, verbose_name='图标颜色')),
            ],
            options={
                'verbose_name': '告警通知渠道',
                'verbose_name_plural': '告警通知渠道',
                'db_table': 'ruyi_alert_notify_config',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AlertTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('cpu_usage', 'CPU使用率'), ('mem_usage', '内存使用率'), ('disk_usage', '磁盘使用率'), ('disk_io', '磁盘IO'), ('network_io', '网络流量'), ('load_avg', '系统负载'), ('ssl_expire', 'SSL证书过期'), ('site_down', '网站宕机'), ('site_slow', '网站响应慢'), ('waf_attack', 'WAF攻击'), ('ssh_fail', 'SSH登录失败'), ('ssh_new_ip', 'SSH新IP登录'), ('panel_login_fail', '面板登录失败'), ('cron_fail', '定时任务失败')], max_length=30, verbose_name='任务类型')),
                ('config', models.TextField(default='{}', verbose_name='任务配置JSON')),
                ('channels', models.TextField(help_text='逗号分隔', verbose_name='通知渠道ID列表')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_trigger', models.DateTimeField(blank=True, null=True, verbose_name='最近触发时间')),
                ('silence_minutes', models.IntegerField(default=30, verbose_name='静默时间(分钟)')),
                ('check_interval', models.IntegerField(default=300, help_text='仅网站宕机类型可配置', verbose_name='检查间隔(秒)')),
            ],
            options={
                'verbose_name': '告警任务',
                'verbose_name_plural': '告警任务',
                'db_table': 'ruyi_alert_task',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='告警内容')),
                ('channels', models.TextField(help_text='逗号分隔', verbose_name='实际发送渠道')),
                ('status', models.SmallIntegerField(choices=[(0, '成功'), (1, '失败')], default=0, verbose_name='发送状态')),
                ('response', models.TextField(blank=True, null=True, verbose_name='响应信息')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysalert.alerttask', verbose_name='告警任务')),
            ],
            options={
                'verbose_name': '告警日志',
                'verbose_name_plural': '告警日志',
                'db_table': 'ruyi_alert_log',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='AlertDailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('date', models.DateField(verbose_name='日期')),
                ('count', models.IntegerField(default=0, verbose_name='发送次数')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysalert.alertnotifyconfig', verbose_name='通知渠道')),
            ],
            options={
                'verbose_name': '每日发送计数',
                'verbose_name_plural': '每日发送计数',
                'db_table': 'ruyi_alert_daily_counter',
                'unique_together': {('config', 'date')},
            },
        ),
    ]
