# Generated by Django 6.0.1 on 2026-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysalert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='channel_type',
            field=models.CharField(default='', max_length=20, verbose_name='渠道类型'),
        ),
        migrations.AddField(
            model_name='alerttask',
            name='push_count',
            field=models.IntegerField(default=10, help_text='0表示不限制', verbose_name='每日推送上限'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='channels',
            field=models.TextField(help_text='渠道名称', verbose_name='实际发送渠道'),
        ),
    ]
