# Generated by Django 6.0.1 on 2026-05-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysalert', '0002_add_push_count_and_channel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttask',
            name='is_alerting',
            field=models.BooleanField(default=False, verbose_name='当前是否告警中'),
        ),
    ]
