# Generated by Django 6.0.1 on 2026-02-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syswaf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wafattacklog',
            name='src_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='IP纬度'),
        ),
        migrations.AddField(
            model_name='wafattacklog',
            name='src_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='IP经度'),
        ),
    ]
