# Generated by Django 6.0.1 on 2026-02-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syswaf', '0002_wafattacklog_src_latitude_wafattacklog_src_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='wafattacklog',
            name='src_city',
            field=models.CharField(default='', max_length=50, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='wafattacklog',
            name='src_country',
            field=models.CharField(default='', max_length=50, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='wafattacklog',
            name='src_province',
            field=models.CharField(default='', max_length=50, verbose_name='省份'),
        ),
    ]
