# Generated by Django 6.0.1 on 2026-02-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syswaf', '0003_wafattacklog_src_city_wafattacklog_src_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wafattacklog',
            name='rule_id',
            field=models.CharField(max_length=50, null=True, verbose_name='触发的规则ID'),
        ),
    ]
