# Generated by Django 6.0.1 on 2026-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syswaf', '0004_alter_wafattacklog_rule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wafglobalconfig',
            name='block_page_config',
            field=models.TextField(default='{}', verbose_name='拦截页面配置'),
        ),
    ]
