# Generated by Django 6.0.1 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syswaf', '0005_wafglobalconfig_block_page_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='wafsiteconfig',
            name='cdn_ip_position',
            field=models.CharField(default='last', help_text='从X-Forwarded-For中获取IP的位置：last取最后一个，first取第一个', max_length=10, verbose_name='CDN真实IP位置'),
        ),
    ]
