# Generated by Django 6.0.1 on 2026-02-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='监控开关')),
                ('log_save_days', models.IntegerField(default=30, verbose_name='日志保存天数')),
                ('log_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='日志存储路径')),
                ('collect_interval', models.IntegerField(default=60, verbose_name='采集间隔(秒)')),
                ('network_interfaces', models.TextField(blank=True, default='[]', null=True, verbose_name='监控网卡列表')),
                ('disk_devices', models.TextField(blank=True, default='[]', null=True, verbose_name='监控磁盘列表')),
            ],
            options={
                'verbose_name': '监控配置',
                'verbose_name_plural': '监控配置',
                'db_table': 'ruyi_monitor_config',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MonitorCpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(db_index=True, verbose_name='记录时间')),
                ('usage_percent', models.FloatField(default=0, verbose_name='CPU使用率(%)')),
                ('cpu_count', models.IntegerField(default=0, verbose_name='CPU逻辑核心数')),
                ('cpu_count_physical', models.IntegerField(default=0, verbose_name='CPU物理核心数')),
                ('cpu_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPU名称')),
                ('top_processes', models.TextField(blank=True, null=True, verbose_name='Top进程列表')),
            ],
            options={
                'verbose_name': 'CPU监控数据',
                'verbose_name_plural': 'CPU监控数据',
                'db_table': 'ruyi_monitor_cpu',
                'ordering': ('-record_time',),
                'indexes': [models.Index(fields=['record_time'], name='ruyi_monito_record__455bed_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonitorDiskIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(db_index=True, verbose_name='记录时间')),
                ('disk_name', models.CharField(db_index=True, default='', max_length=50, verbose_name='磁盘名称')),
                ('read_bytes', models.FloatField(default=0, verbose_name='读取速率(B/s)')),
                ('write_bytes', models.FloatField(default=0, verbose_name='写入速率(B/s)')),
                ('read_count', models.IntegerField(default=0, verbose_name='读取次数(次/s)')),
                ('write_count', models.IntegerField(default=0, verbose_name='写入次数(次/s)')),
                ('read_time', models.IntegerField(default=0, verbose_name='读取耗时(ms/s)')),
                ('write_time', models.IntegerField(default=0, verbose_name='写入耗时(ms/s)')),
                ('total_read_bytes', models.BigIntegerField(default=0, verbose_name='累计读取字节数')),
                ('total_write_bytes', models.BigIntegerField(default=0, verbose_name='累计写入字节数')),
                ('top_processes', models.TextField(blank=True, null=True, verbose_name='Top进程列表')),
            ],
            options={
                'verbose_name': '磁盘IO监控数据',
                'verbose_name_plural': '磁盘IO监控数据',
                'db_table': 'ruyi_monitor_disk_io',
                'ordering': ('-record_time',),
                'indexes': [models.Index(fields=['record_time'], name='ruyi_monito_record__6df499_idx'), models.Index(fields=['disk_name'], name='ruyi_monito_disk_na_97970c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonitorLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(db_index=True, verbose_name='记录时间')),
                ('load_one', models.FloatField(default=0, verbose_name='1分钟负载')),
                ('load_five', models.FloatField(default=0, verbose_name='5分钟负载')),
                ('load_fifteen', models.FloatField(default=0, verbose_name='15分钟负载')),
                ('usage_percent', models.FloatField(default=0, verbose_name='负载使用率(%)')),
                ('cpu_count', models.IntegerField(default=0, verbose_name='CPU核心数')),
                ('top_processes', models.TextField(blank=True, null=True, verbose_name='Top进程列表')),
            ],
            options={
                'verbose_name': '系统负载监控数据',
                'verbose_name_plural': '系统负载监控数据',
                'db_table': 'ruyi_monitor_load',
                'ordering': ('-record_time',),
                'indexes': [models.Index(fields=['record_time'], name='ruyi_monito_record__a14fd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonitorMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(db_index=True, verbose_name='记录时间')),
                ('usage_percent', models.FloatField(default=0, verbose_name='内存使用率(%)')),
                ('mem_total', models.FloatField(default=0, verbose_name='内存总量(MB)')),
                ('mem_used', models.FloatField(default=0, verbose_name='内存已用(MB)')),
                ('mem_free', models.FloatField(default=0, verbose_name='内存空闲(MB)')),
                ('mem_available', models.FloatField(default=0, verbose_name='内存可用(MB)')),
                ('mem_buffers', models.FloatField(blank=True, default=0, null=True, verbose_name='Buffers(MB)')),
                ('mem_cached', models.FloatField(blank=True, default=0, null=True, verbose_name='Cached(MB)')),
                ('top_processes', models.TextField(blank=True, null=True, verbose_name='Top进程列表')),
            ],
            options={
                'verbose_name': '内存监控数据',
                'verbose_name_plural': '内存监控数据',
                'db_table': 'ruyi_monitor_memory',
                'ordering': ('-record_time',),
                'indexes': [models.Index(fields=['record_time'], name='ruyi_monito_record__0c185a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonitorNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(db_index=True, verbose_name='记录时间')),
                ('interface_name', models.CharField(db_index=True, default='', max_length=50, verbose_name='网卡名称')),
                ('up_bytes', models.FloatField(default=0, verbose_name='上行速率(B/s)')),
                ('up_packets', models.IntegerField(default=0, verbose_name='上行包数(个/s)')),
                ('up_err', models.IntegerField(default=0, verbose_name='上行错误包数(个/s)')),
                ('up_drop', models.IntegerField(default=0, verbose_name='上行丢弃包数(个/s)')),
                ('down_bytes', models.FloatField(default=0, verbose_name='下行速率(B/s)')),
                ('down_packets', models.IntegerField(default=0, verbose_name='下行包数(个/s)')),
                ('down_err', models.IntegerField(default=0, verbose_name='下行错误包数(个/s)')),
                ('down_drop', models.IntegerField(default=0, verbose_name='下行丢弃包数(个/s)')),
                ('total_up_bytes', models.BigIntegerField(default=0, verbose_name='累计上行字节数')),
                ('total_down_bytes', models.BigIntegerField(default=0, verbose_name='累计下行字节数')),
            ],
            options={
                'verbose_name': '网络监控数据',
                'verbose_name_plural': '网络监控数据',
                'db_table': 'ruyi_monitor_network',
                'ordering': ('-record_time',),
                'indexes': [models.Index(fields=['record_time'], name='ruyi_monito_record__b3bb80_idx'), models.Index(fields=['interface_name'], name='ruyi_monito_interfa_ba1614_idx')],
            },
        ),
    ]
