services:
  RUYI_DKAPP:
    image: phpmyadmin:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPU}
          memory: ${MEM}
    restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    volumes:
      - ${APP_PATH}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ${APP_PATH}/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    labels:
      createdBy: "ruyi_apps"
    networks:
      - ruyi-network

networks:
  ruyi-network:
    external: true