# Generated by Django 5.0.3 on 2025-02-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RyDocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=100, verbose_name='容器名称')),
                ('image_name', models.CharField(max_length=100, verbose_name='镜像名称')),
                ('install_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='安装版本')),
                ('is_appstore', models.BooleanField(default=False, verbose_name='是否商店应用')),
                ('ports', models.TextField(blank=True, null=True, verbose_name='端口映射')),
                ('network', models.TextField(blank=True, null=True, verbose_name='网络')),
                ('status', models.CharField(choices=[('', '未知'), ('paused', '已暂停'), ('running', '已启动'), ('exited', '已停止')], default='', max_length=50, verbose_name='状态')),
            ],
            options={
                'verbose_name': '容器',
                'verbose_name_plural': '容器',
                'db_table': 'ruyi_docker',
                'ordering': ('-create_at',),
            },
        ),
    ]
