# Generated by Django 5.0.3 on 2025-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdocker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RyDockerRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('url', models.TextField(blank=True, null=True, verbose_name='仓库URL')),
                ('protocol', models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=30, verbose_name='协议')),
                ('is_auth', models.BooleanField(default=False, verbose_name='是否认证')),
                ('username', models.CharField(max_length=100, verbose_name='仓库用户名')),
                ('password', models.CharField(max_length=200, verbose_name='仓库密码')),
            ],
            options={
                'verbose_name': '容器仓库',
                'verbose_name_plural': '容器仓库',
                'db_table': 'ruyi_docker_repo',
                'ordering': ('-create_at',),
            },
        ),
    ]
