# Generated by Django 5.0.3 on 2025-02-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdocker', '0002_rydockerrepo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rydockerrepo',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='仓库密码'),
        ),
        migrations.AlterField(
            model_name='rydockerrepo',
            name='protocol',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='https', max_length=30, verbose_name='协议'),
        ),
        migrations.AlterField(
            model_name='rydockerrepo',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='仓库用户名'),
        ),
    ]
