# Generated by Django 5.0.3 on 2025-03-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdocker', '0003_alter_rydockerrepo_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RyDockerApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('appid', models.IntegerField(blank=True, default=0, null=True, verbose_name='所属应用id')),
                ('appname', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属应用名称')),
                ('name', models.CharField(max_length=100, verbose_name='应用名称')),
                ('version', models.CharField(max_length=30, verbose_name='安装版本')),
                ('cpu', models.IntegerField(default=0, verbose_name='cpu限制')),
                ('mem', models.IntegerField(default=0, verbose_name='内存限制')),
                ('allowport', models.BooleanField(default=False, verbose_name='放通外网端口')),
                ('advanced', models.BooleanField(default=False, verbose_name='高级配置')),
                ('params', models.TextField(blank=True, null=True, verbose_name='环境参数字典')),
            ],
            options={
                'verbose_name': '容器广场APP',
                'verbose_name_plural': '容器广场APP',
                'db_table': 'ruyi_docker_apps',
                'ordering': ('-create_at',),
            },
        ),
    ]
