# Generated by Django 5.0.3 on 2025-03-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdocker', '0004_rydockerapps'),
    ]

    operations = [
        migrations.AddField(
            model_name='rydockerapps',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所属应用类型'),
        ),
    ]
