# Generated by Django 5.1.7 on 2025-03-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdocker', '0005_rydockerapps_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rydockerapps',
            name='status',
            field=models.CharField(choices=[('install', '安装中'), ('paused', '已暂停'), ('running', '已启动'), ('exited', '已停止')], default='install', max_length=50, verbose_name='状态'),
        ),
    ]
