# Generated by Django 6.0.1 on 2026-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdocker', '0006_rydockerapps_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rydockerapps',
            name='status',
            field=models.CharField(choices=[('install', '安装中'), ('install_failed', '安装失败'), ('paused', '已暂停'), ('running', '已启动'), ('exited', '已停止'), ('created', '已创建'), ('restarting', '重启中'), ('removing', '移除中'), ('dead', '已结束')], default='install', max_length=50, verbose_name='状态'),
        ),
    ]
