# Generated by Django 5.0.3 on 2024-11-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
                ('module', models.CharField(blank=True, choices=[('dbmg', '数据库管理'), ('login', '用户登录'), ('safe', '安全'), ('softmg', '软件管理'), ('filemg', '文件管理'), ('sitemg', '网站管理'), ('dellog', '清空日志'), ('panelst', '面板设置'), ('taskmg', '计划任务')], max_length=255, null=True, verbose_name='请求模块')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='请求地址')),
                ('body', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='请求ip地址')),
                ('ip_area', models.CharField(blank=True, help_text='IP归属地', max_length=100, null=True, verbose_name='IP归属地')),
                ('browser', models.CharField(blank=True, max_length=64, null=True, verbose_name='请求浏览器')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('request_os', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='自定义内容')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'ruyi_operation_log',
                'ordering': ('-create_at',),
            },
        ),
    ]
