# Generated by Django 5.0.3 on 2025-02-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syslogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='请求ip地址'),
        ),
    ]
