# Generated by Django 5.0.3 on 2025-02-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syslogs', '0002_alter_operationlog_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='module',
            field=models.CharField(blank=True, choices=[('dbmg', '数据库管理'), ('login', '用户登录'), ('safe', '安全'), ('softmg', '软件管理'), ('filemg', '文件管理'), ('sitemg', '网站管理'), ('dellog', '清空日志'), ('panelst', '面板设置'), ('taskmg', '计划任务'), ('dockermg', '容器')], max_length=255, null=True, verbose_name='请求模块'),
        ),
    ]
